name: lint and format check

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.py"
      - "**/pyproject.toml"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.py"
      - "**/pyproject.toml"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@30ce38e20653a26dd16caa082b010cec334ccf56 # v3.5.1
        with:
          version: "0.9.7"

      - name: Set up Python
        run: uv python install 3.13.7

      - name: Install dependencies
        run: uv sync --group dev

      - name: Install and run ruff format check
        uses: astral-sh/ruff-action@4ac3c5ec5652cc235ceeac069541cd5c630e7e3d # v3.5.1
        with:
          args: "format --check --diff"

      - name: Run ruff check
        uses: astral-sh/ruff-action@4ac3c5ec5652cc235ceeac069541cd5c630e7e3d # v3.5.1
        with:
          args: "check . --config pyproject.toml"

      - name: Run mypy
        run: uv run mypy --config pyproject.toml
