name: lint and format check

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.py"
      - "**/pyproject.toml"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.py"
      - "**/pyproject.toml"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
        with:
          version: "0.9.10"

      - run: uv python install 3.13.7

      - run: uv sync --all-packages --extra dev

      - uses: astral-sh/ruff-action@b08f7b47e5c97c539fcd4ccc6dc06a64a6621742 # v3.5.1
        with:
          args: "format --check --diff"

      - uses: astral-sh/ruff-action@b08f7b47e5c97c539fcd4ccc6dc06a64a6621742 # v3.5.1
        with:
          args: "check"

      - run: uv run mypy .
