name: lint and format check

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.py"
      - "**/pyproject.toml"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.py"
      - "**/pyproject.toml"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7.1.3
        with:
          version: "0.9.10"

      - run: uv python install 3.13.7

      - run: uv sync --extra dev --package megaloader

      - uses: astral-sh/ruff-action@e7baf99fcc269796ae85308f7bef6b06147c7f08 # v3.5.1
        with:
          args: "format --check --diff"

      - uses: astral-sh/ruff-action@e7baf99fcc269796ae85308f7bef6b06147c7f08 # v3.5.1
        with:
          args: "check"

      - run: uv run mypy .
