name: lint and format check

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.py"
      - "**/pyproject.toml"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.py"
      - "**/pyproject.toml"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@be7fc19b4169c26a2aa1b8a430af391f2a96b3c9 # v7.1.4
        with:
          version: "0.9.10"

      - run: uv python install 3.13.7

      - name: Install workspace dependencies
        run: uv sync --all-packages --extra dev

      - name: Install API dependencies
        run: cd apps/api && uv sync --extra dev

      - uses: astral-sh/ruff-action@1e133b7cccb09f5024f3622a8ff61e947c6a1603 # v3.5.1
        with:
          args: "format --check --diff"

      - uses: astral-sh/ruff-action@1e133b7cccb09f5024f3622a8ff61e947c6a1603 # v3.5.1
        with:
          args: "check"

      - name: Type check workspace
        run: uv run mypy --exclude apps/api .

      - name: Type check API
        run: cd apps/api && uv run mypy .
