name: lint and format check

on:
  push:
    branches: [main]
    paths:
      - "**/*.py"
  pull_request:
    branches: [main]
    paths:
      - "**/*.py"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13.7"

      - name: Install and run ruff format check
        uses: astral-sh/ruff-action@4ac3c5ec5652cc235ceeac069541cd5c630e7e3d # v3.5.1
        with:
          args: "format --check --diff"

      - name: Run ruff check
        uses: astral-sh/ruff-action@4ac3c5ec5652cc235ceeac069541cd5c630e7e3d # v3.5.1
        with:
          args: "check . --config pyproject.toml"

      - name: Install dev dependencies
        run:
          python -m pip install --upgrade pip && python -m pip install -r
          requirements-dev.txt

      - name: Run mypy
        run: mypy megaloader --config pyproject.toml
