name: release-cli

on:
  push:
    tags: ["vcli-*.*.*"]

jobs:
  build-pkg:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@be7fc19b4169c26a2aa1b8a430af391f2a96b3c9 # v7.1.4
        with:
          version: "0.9.10"
          python-version: "3.13.7"

      - run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/vcli-}"
          CLI_PKG_VERSION=$(grep '^version = ' packages/cli/pyproject.toml | cut -d'"' -f2)
          if [ "$TAG_VERSION" != "$CLI_PKG_VERSION" ]; then
            echo "Tag $TAG_VERSION != cli package $CLI_PKG_VERSION"
            exit 1
          fi

      - run: uv build --package megaloader-cli

      - uses: actions/upload-artifact@v5
        with:
          name: cli-pkg-dist
          path: dist/*

  build-bin:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@be7fc19b4169c26a2aa1b8a430af391f2a96b3c9 # v7.1.4
        with:
          version: "0.9.10"
          python-version: "3.13.7"

      - run: uv venv

      - run: uv pip install -e packages/core -e packages/cli

      - run: uv pip install pyinstaller

      - run:
          uv run pyinstaller --onefile --name megaloader-cli-${{ matrix.os == 'ubuntu-latest' && 'linux' || 'windows' }} --paths
          packages/core packages/cli/megaloader_cli/main.py
        shell: bash

      - uses: actions/upload-artifact@v5
        with:
          name: cli-bin-${{ matrix.os }}
          path: dist/*

  pypi-cli:
    needs: build-pkg
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/project/megaloader-cli

    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v5
        with:
          name: cli-pkg-dist
          path: dist

      - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          packages-dir: dist/
          print-hash: true

  github:
    needs: [build-pkg, build-bin]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v5
        with:
          name: cli-pkg-dist
          path: dist
      - uses: actions/download-artifact@v5
        with:
          name: cli-bin-ubuntu-latest
          path: dist
      - uses: actions/download-artifact@v5
        with:
          name: cli-bin-windows-latest
          path: dist
      - uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: dist/*
          generate_release_notes: true
