name: tests

on:
  schedule:
    - cron: "0 5 * * 1" # Run at 05:00 UTC every Monday
  # push:
  #   branches: ["main"]
  #   paths:
  #     - "pyproject.toml"
  #     - "packages/core/**/*.py"
  #     - "packages/core/pyproject.toml"
  # pull_request:
  #   branches: ["main"]
  #   paths:
  #     - "pyproject.toml"
  #     - "packages/core/**/*.py"
  #     - "packages/core/pyproject.toml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v3.5.1
        with:
          version: "0.9.10"

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --extra dev --package megaloader

      - name: Run tests
        run:
          uv run pytest -v --tb=short --junitxml=junit.xml -o
          junit_family=legacy

      - name: Coverage & codecov (3.13 only)
        if: matrix.python-version == '3.13'
        run: |
          uv run --with pytest-cov pytest \
            --run-live \
            --cov=megaloader \
            --cov-report=xml \
            --cov-report=term \
            --junitxml=junit.xml \
            -o junit_family=legacy
        continue-on-error: true

      - if: matrix.python-version == '3.13'
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          files: ./coverage.xml

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          files: ./junit.xml
          report_type: test_results
